"""Professional report generator - HTML, JSON, TXT."""
import json
from datetime import datetime
from pathlib import Path
from typing import Optional
from ..utils.helpers import status, save_json

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VenomScan - Penetration Test Report</title>
    <style>
        *{margin:0;padding:0;box-sizing:border-box}
        body{font-family:'Segoe UI',sans-serif;background:#0a0a0a;color:#e0e0e0;line-height:1.6}
        .container{max-width:1200px;margin:0 auto;padding:20px}
        .header{background:linear-gradient(135deg,#8b0000,#ff0000);padding:30px;text-align:center;border-radius:8px;margin-bottom:30px}
        .header h1{color:#fff;font-size:2.5em}
        .header p{color:#ffcccc;margin-top:10px}
        .section{background:#1a1a1a;border:1px solid #333;border-radius:8px;padding:20px;margin:20px 0}
        .section h2{color:#ff4444;border-bottom:2px solid #ff0000;padding-bottom:10px;margin-bottom:15px}
        .finding{background:#222;border-left:4px solid #ff0000;padding:15px;margin:10px 0;border-radius:4px}
        .finding.critical{border-color:#ff0000;background:#2a0000}
        .finding.high{border-color:#ff6600;background:#2a1000}
        .finding.medium{border-color:#ffcc00;background:#2a2a00}
        .finding.low{border-color:#00ccff;background:#002a2a}
        .finding.info{border-color:#666;background:#1a1a1a}
        .badge{display:inline-block;padding:3px 10px;border-radius:3px;font-weight:bold;font-size:0.85em;margin-right:10px}
        .badge.critical{background:#ff0000;color:#fff}
        .badge.high{background:#ff6600;color:#fff}
        .badge.medium{background:#ffcc00;color:#000}
        .badge.low{background:#00ccff;color:#000}
        table{width:100%;border-collapse:collapse;margin:10px 0}
        th,td{padding:10px;text-align:left;border-bottom:1px solid #333}
        th{background:#2a0000;color:#ff4444}
        tr:hover{background:#222}
        .footer{text-align:center;padding:20px;color:#666;margin-top:40px}
        code{background:#000;padding:2px 6px;border-radius:3px;color:#0f0}
        pre{background:#000;padding:15px;border-radius:5px;overflow-x:auto;color:#0f0}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🐍 VenomScan</h1>
            <p>Advanced Web Application Penetration Test Report</p>
        </div>

        <div class="section">
            <h2>📋 Executive Summary</h2>
            <table>
                <tr><th>Target</th><td>{{target}}</td></tr>
                <tr><th>Date</th><td>{{date}}</td></tr>
                <tr><th>CMS</th><td>{{cms}}</td></tr>
                <tr><th>Version</th><td>{{version}}</td></tr>
                <tr><th>Total Findings</th><td>{{total_findings}}</td></tr>
                <tr><th>Critical</th><td style="color:#ff0000;font-weight:bold">{{critical_count}}</td></tr>
                <tr><th>High</th><td style="color:#ff6600;font-weight:bold">{{high_count}}</td></tr>
                <tr><th>Medium</th><td style="color:#ffcc00;font-weight:bold">{{medium_count}}</td></tr>
                <tr><th>Low</th><td style="color:#00ccff;font-weight:bold">{{low_count}}</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>🔍 Reconnaissance</h2>
            <table>
                {{recon_table}}
            </table>
        </div>

        <div class="section">
            <h2>⚠️ Findings</h2>
            {{findings_html}}
        </div>

        <div class="footer">
            <p>Generated by VenomScan v2.0 | For authorized security testing only</p>
            <p>{{timestamp}}</p>
        </div>
    </div>
</body>
</html>"""

class ReportGenerator:
    """Generates professional pentest reports."""

    def __init__(self, target: str, findings: list, cms_info: dict):
        self.target = target
        self.findings = findings
        self.cms_info = cms_info
        self.report_data = {
            "target": target,
            "date": datetime.now().isoformat(),
            "cms": cms_info.get("cms", "unknown"),
            "version": cms_info.get("version", "unknown"),
            "findings": findings,
            "total_findings": len(findings),
            "critical_count": sum(1 for f in findings if f.get("severity") == "CRITICAL"),
            "high_count": sum(1 for f in findings if f.get("severity") == "HIGH"),
            "medium_count": sum(1 for f in findings if f.get("severity") == "MEDIUM"),
            "low_count": sum(1 for f in findings if f.get("severity") == "LOW"),
        }

    def to_json(self, filepath: str = None) -> str:
        """Export as JSON."""
        if not filepath:
            filepath = f"data/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        save_json(self.report_data, filepath)
        return filepath

    def to_html(self, filepath: str = None) -> str:
        """Export as HTML report."""
        if not filepath:
            filepath = f"data/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"

        # Build findings HTML
        findings_html = ""
        for f in self.findings:
            sev = f.get("severity", "INFO").lower()
            findings_html += f"""<div class="finding {sev}">
                <span class="badge {sev}">{f.get('severity', 'INFO')}</span>
                <strong>{f.get('type', 'Unknown')}</strong>
                <p>URL: <code>{f.get('url', 'N/A')}</code></p>
                <p>Payload: <code>{str(f.get('payload', 'N/A'))[:100]}</code></p>
                <p>Evidence: {f.get('evidence', f.get('description', 'N/A'))}</p>
                {f'<p>CVSS: {f.get("cvss", "N/A")}</p>' if f.get("cvss") else ''}
            </div>\n"""

        # Build recon table
        recon_rows = ""
        if self.cms_info.get("components"):
            for c in self.cms_info["components"]:
                recon_rows += f"<tr><td>Component</td><td><code>{c['name']}</code></td><td>{c['description']}</td></tr>\n"
        if self.cms_info.get("interesting_files"):
            for fl in self.cms_info["interesting_files"]:
                recon_rows += f"<tr><td>File</td><td><code>{fl.get('path', 'N/A')}</code></td><td>Exposed</td></tr>\n"
        if self.cms_info.get("admin_url"):
            recon_rows += f"<tr><td>Admin Panel</td><td><code>{self.cms_info['admin_url']}</code></td><td>Accessible</td></tr>\n"
        if not recon_rows:
            recon_rows = "<tr><td colspan='3'>No recon data</td></tr>"

        # Populate template
        html = HTML_TEMPLATE
        html = html.replace("{{target}}", self.target)
        html = html.replace("{{date}}", self.report_data["date"])
        html = html.replace("{{cms}}", self.report_data["cms"].upper())
        html = html.replace("{{version}}", self.report_data["version"])
        html = html.replace("{{total_findings}}", str(self.report_data["total_findings"]))
        html = html.replace("{{critical_count}}", str(self.report_data["critical_count"]))
        html = html.replace("{{high_count}}", str(self.report_data["high_count"]))
        html = html.replace("{{medium_count}}", str(self.report_data["medium_count"]))
        html = html.replace("{{low_count}}", str(self.report_data["low_count"]))
        html = html.replace("{{recon_table}}", recon_rows)
        html = html.replace("{{findings_html}}", findings_html)
        html = html.replace("{{timestamp}}", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        status(f"HTML report saved: {filepath}", "success")
        return filepath

    def to_text(self, filepath: str = None) -> str:
        """Export as plain text."""
        if not filepath:
            filepath = f"data/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

        lines = []
        lines.append("=" * 70)
        lines.append("VENOMSCAN - Penetration Test Report")
        lines.append("=" * 70)
        lines.append(f"\nTarget: {self.target}")
        lines.append(f"Date: {self.report_data['date']}")
        lines.append(f"CMS: {self.report_data['cms']} {self.report_data['version']}")
        lines.append(f"\nTotal Findings: {self.report_data['total_findings']}")
        lines.append(f"  Critical: {self.report_data['critical_count']}")
        lines.append(f"  High: {self.report_data['high_count']}")
        lines.append(f"  Medium: {self.report_data['medium_count']}")
        lines.append(f"  Low: {self.report_data['low_count']}")

        if self.cms_info.get("admin_url"):
            lines.append(f"\nAdmin Panel: {self.cms_info['admin_url']}")
        if self.cms_info.get("components"):
            lines.append("\nComponents:")
            for c in self.cms_info["components"]:
                lines.append(f"  - {c['name']}: {c['description']}")

        lines.append("\n" + "-" * 70)
        lines.append("FINDINGS")
        lines.append("-" * 70)

        for i, f in enumerate(self.findings, 1):
            lines.append(f"\n{i}. [{f.get('severity', '?')}] {f.get('type', 'Unknown')}")
            lines.append(f"   URL: {f.get('url', 'N/A')}")
            lines.append(f"   Payload: {f.get('payload', 'N/A')}")
            if f.get("evidence"):
                lines.append(f"   Evidence: {f['evidence']}")
            if f.get("cvss"):
                lines.append(f"   CVSS: {f['cvss']}")

        lines.append("\n" + "=" * 70)
        lines.append("Generated by VenomScan v2.0")
        lines.append("=" * 70)

        text = "\n".join(lines)
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(text)

        status(f"Text report saved: {filepath}", "success")
        return filepath
