plugins {
    id 'com.android.application'
}

android {
    namespace 'com.invisible'
    compileSdk 34

    defaultConfig {
        applicationId "com.android.system.service"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled false
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // إخفاء اسم الحزمة من التطبيق بعد البناء
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "SystemUpdate.apk"
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
}
